import datetime

with open("Untitled.mp", "rt", encoding='windows-1251') as file:

    lines = file.readlines()


coordList = []
steps = []
newCoordList = []
trackCoordArr = []
maxStep = 40  # - максималный непрерывный шаг в треках
trackCount = 0  # - количество полученных треков


def track_step_length(point1, point2):

    return 1000 * ((point2[0] - point1[0]) ** 2 + (point2[1] - point1[1]) ** 2) ** .5


for line in lines:

    if line.find("Data0") == 0:

        coordList.append(list(
            map(lambda x: list(map(float, x.split(","))), line.strip().lstrip("Data0=(").rstrip(")").split("),("))))

for track in coordList:

    trackCoordArr = [track[0]]
    trackCount = trackCount + 1

    for _ in range(len(track) - 1):

        if track_step_length(track[_], track[_ + 1]) > maxStep and len(trackCoordArr) > 0:

            newCoordList.append(trackCoordArr)
            trackCoordArr = [track[_ + 1]]
            trackCount = trackCount + 1
        else:

            trackCoordArr.append(track[_ + 1])

        steps.append(track_step_length(track[_], track[_ + 1]))

    if len(trackCoordArr) > 0:

        newCoordList.append(trackCoordArr)

steps.sort(reverse=True)
print("Список шагов:", steps, "\n")
print("Список координат обработанных треков:", newCoordList, "\n")
print("trackCount =", trackCount)
newFile = '''; Generated by GPSMapEdit 2.1.78.9

[IMG ID]
CodePage=1251
LblCoding=9
ID=''' + datetime.datetime.today().strftime("%Y%m%d") + '''
Name=треки''' + datetime.datetime.today().strftime("%Y%m%d") + '''
Preprocess=G
TreSize=511
TreMargin=0.00000
RgnLimit=127
POIIndex=N
Levels=4
Level0=24
Level1=20
Level2=16
Level3=14
Zoom0=0
Zoom1=1
Zoom2=2
Zoom3=3
[END-IMG ID]

'''

for track in newCoordList:

    newFile = newFile + '''

[POLYLINE]
Type=0x2a
EndLevel=3
Data0='''

    for coord in track:
        newFile = newFile + "(" + str(coord[0]) + "," + str(coord[1]) + "),"

    newFile = newFile.rstrip(",")

newFile = newFile + "\n[END]"

with open("newTracks.mp", "wt", encoding='windows-1251') as file:

    file.writelines(newFile)

#print(newFile)
